---
- name: install redis master
  hosts: master
  sudo: yes
  vars:
    - redis_bind: 192.168.3.25
  roles:
    - { role: redis }

- name: install redis slaves
  hosts: slave
  sudo: yes
  vars:
    - redis_slaveof: 192.168.3.25 6379
    - redis_bind: 192.168.3.26
  roles:
    - { role: redis }
