---

- name: Install redis through package.
  apt: name=redis-server state=latest

- name: Copy redis configuration
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf  mode=0644
  notify:
  - restart redis-server
